keys:
  - &user_e-psi-lon "age1kgu5c0xcajwg3wnc39s5ulg3ktsz405x65sp3wqgpay2tncgqfrqs5s5s8"
  - &host_asus "age1sgy75g9y78e4s5kh420cgu9u8yt3k9u27yxjvvtu7czwtct3s49s0h8q3r"
  - &host_hp "age1eva2w8azzuw4nunuy4t0tjn0ajfcj525e58j59j6hleu5gxdav5qgcgf34"

creation_rules:
  - path_regex: resources/secrets/.*\.asus\.[^/]+$
    key_groups:
      - age:
          - *user_e-psi-lon
          - *host_asus

  - path_regex: resources/secrets/.*\.hp\.[^/]+$
    key_groups:
      - age:
          - *user_e-psi-lon
          - *host_hp

  - path_regex: resources/secrets/.*\.e-psi-lon\.[^/]+$
    key_groups:
      - age:
          - *user_e-psi-lon

  - path_regex: resources/secrets/.*\.shared\.[^/]+$
    key_groups:
      - age:
          - *user_e-psi-lon
          - *host_asus
          - *host_hp

  - path_regex: resources/secrets/.*
    key_groups:
      - age:
          - *user_e-psi-lon
          - *host_asus
          - *host_hp