# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a45818e0-7998-4e3c-9550-8eee4017f18b";
    fsType = "btrfs";
  };

  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/993e6b9f-bea1-4a16-95f6-5b6eb2badbb7";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/90cc5a25-e3d2-486f-a6a3-73d4cffd8514";
    fsType = "btrfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/1062ba32-68f8-4abf-aedd-06d2c162d4fa"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
