name: Export ready to stow

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:  # Allow manual trigger

jobs:
    stow:
        runs-on: ubuntu-latest
        steps:
          - name: Placeholder
            run: echo "Not implemented yet"
